/* Document drafts have a dedicated store; no timetable or textbook writes. */
(()=>{'use strict';
const KEY='college_document_drafts_v1', $=id=>document.getElementById(id), fields=['number','date','agency','phone','subject','recipient','reference','attachments','signer','position','body','notes'];
let drafts=[],current=null,dirty=false,readFailed=false;
try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(raw))throw Error();drafts=raw;}catch(e){readFailed=true;alert('อ่านข้อมูลฉบับร่างไม่ได้ ระบบจะไม่เขียนทับข้อมูลเดิม กรุณาเก็บข้อมูลเบราว์เซอร์ไว้');}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=t=>t==='internal'?'หนังสือภายใน':'หนังสือภายนอก';
const uuid=()=>crypto.randomUUID?crypto.randomUUID():'doc'+Date.now()+Math.random().toString(36).slice(2);
function persist(next){if(readFailed){alert('ข้อมูลเดิมอ่านไม่ได้ จึงไม่สามารถบันทึกทับได้');return false;}try{localStorage.setItem(KEY,JSON.stringify(next));drafts=next;return true;}catch(e){alert('บันทึกไม่สำเร็จ พื้นที่จัดเก็บอาจเต็ม กรุณาสำรองข้อมูล');return false;}}
function render(){const q=$('docSearch').value.trim().toLowerCase(),type=$('docFilter').value;const rows=drafts.filter(d=>(type==='all'||d.type===type)&&[d.subject,d.number,d.recipient].join(' ').toLowerCase().includes(q)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('docList').innerHTML=rows.length?'<table><thead><tr><th>ประเภท</th><th>เลขหนังสือ</th><th>เรื่อง / ผู้รับ</th><th>แก้ไขล่าสุด</th><th>จัดการ</th></tr></thead><tbody>'+rows.map(d=>`<tr><td>${label(d.type)}</td><td>${esc(d.number)||'—'}</td><td><b>${esc(d.subject)}</b><br>${esc(d.recipient)}</td><td>${esc(new Date(d.updatedAt).toLocaleString('th-TH'))}</td><td><button class="btn light" data-edit="${esc(d.id)}">เปิด / แก้ไข</button> <button class="btn light" data-copy="${esc(d.id)}">ทำสำเนา</button> <button class="btn light" data-delete="${esc(d.id)}">ลบ</button></td></tr>`).join('')+'</tbody></table>':'<p class="muted">ยังไม่มีฉบับร่างที่ตรงกับรายการนี้</p>';}
function leave(){return !dirty||confirm('มีข้อมูลที่ยังไม่ได้บันทึก ต้องการทิ้งการแก้ไขหรือไม่?');}
function open(d){if(!leave())return;current={...d};fields.forEach(k=>$( 'doc_'+k).value=d[k]||'');$('docEditorTitle').textContent=label(d.type)+' • ฉบับร่าง';$('docEditor').hidden=false;$('docStatus').textContent='กรอกข้อมูลแล้วกดบันทึกฉบับร่าง';dirty=false;$('docEditor').scrollIntoView({behavior:'smooth',block:'start'});}
function fresh(type){const now=new Date();open({id:uuid(),type,date:`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,agency:'วิทยาลัยเทคนิคปากช่อง'});}
$('docNewInternal').onclick=()=>fresh('internal');$('docNewExternal').onclick=()=>fresh('external');
$('docForm').oninput=()=>{dirty=true;$('docStatus').textContent='มีการแก้ไขที่ยังไม่ได้บันทึก';};
$('docForm').onsubmit=e=>{e.preventDefault();if(!current)return;const d={...current};fields.forEach(k=>d[k]=$('doc_'+k).value.trim());if(!d.subject){$('docStatus').textContent='กรุณากรอกเรื่องก่อนบันทึก';$('doc_subject').focus();return;}d.updatedAt=new Date().toISOString();d.createdAt=d.createdAt||d.updatedAt;if(persist([...drafts.filter(x=>x.id!==d.id),d])){current=d;dirty=false;render();$('docStatus').textContent='บันทึกฉบับร่างเรียบร้อยแล้ว';}};
$('docClose').onclick=()=>{if(leave()){dirty=false;current=null;$('docEditor').hidden=true;}};
$('docSearch').oninput=render;$('docFilter').onchange=render;
$('docList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.edit||b.dataset.copy||b.dataset.delete,d=drafts.find(x=>x.id===id);if(!d)return;if(b.dataset.edit)open(d);else if(b.dataset.copy)open({...d,id:uuid(),number:'',subject:d.subject+' (สำเนา)',createdAt:null});else if(confirm('ลบฉบับร่าง “'+d.subject+'” หรือไม่?')){if(current?.id===id&&!leave())return;if(persist(drafts.filter(x=>x.id!==id))){if(current?.id===id){dirty=false;current=null;$('docEditor').hidden=true;}render();}}};
$('docBackup').onclick=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify({format:KEY,drafts},null,2)],{type:'application/json'}));a.href=u;a.download='college-document-drafts.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};
$('docRestore').onclick=()=>$('docImport').click();
$('docImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error();const data=JSON.parse(await f.text());if(data.format!==KEY||!Array.isArray(data.drafts)||data.drafts.some(d=>!d||!['internal','external'].includes(d.type)||typeof d.subject!=='string'||fields.some(k=>d[k]!=null&&typeof d[k]!=='string')))throw Error();if(!data.drafts.length){alert('ไฟล์นี้ไม่มีฉบับร่าง');return;}if(!confirm('นำเข้า '+data.drafts.length+' ฉบับเป็นสำเนาใหม่ โดยเก็บรายการเดิมไว้หรือไม่?'))return;const now=new Date().toISOString();const imported=data.drafts.map(d=>Object.assign(Object.fromEntries(fields.map(k=>[k,d[k]||''])),{id:uuid(),type:d.type,createdAt:now,updatedAt:now}));if(persist([...drafts,...imported])){render();alert('นำเข้าฉบับร่างเรียบร้อยแล้ว');}}catch(e){alert('นำเข้าไม่ได้ กรุณาเลือกไฟล์สำรองฉบับร่างที่ถูกต้อง ขนาดไม่เกิน 10 MB');}finally{$('docImport').value='';}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
document.getElementById('nav').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b&&document.getElementById('documentsPage').classList.contains('active')&&b.dataset.page!=='documentsPage'&&!leave()){e.preventDefault();e.stopImmediatePropagation();}},true);
render();
})();
